### ISSUE TITLE
Could you add your local_manifest(xiaomi_tiffany) on this repository

### ISSUE THREAD

**Issue by aerzha** [windbell-project/manifest#1]
hi:
i have synced the aospextended resource, but when i "lunch aosp_tiffany-userdebug", it seems like still missing some code.  Could you please give me your local_manifest, thanks a lot.

**Comment by kidachiP** [comment]
<manifest>
<remote name="windbell-project" fetch="https://github.com/windbell-project" pushurl="ssh://git@github.com/windbell-project" revision="lineage-16.0"/>
<project path="kernel/xiaomi/msm8953" name="android_kernel_xiaomi_msm8953" remote="windbell-project" revision="lineage-16.0"/>
<project path="device/xiaomi/msm8953-common" name="android_device_xiaomi_msm8953-common" remote="windbell-project" revision="9.x"/>
<project path="device/xiaomi/tiffany" name="android_device_xiaomi_tiffany" remote="windbell-project" revision="9.x"/>
<project path="vendor/xiaomi" name="proprietary_vendor_xiaomi" remote="windbell-project" revision="lineage-16.0"/>
<project name="soshiweekly/vendor_xiaomi_MiuiCamera" path="vendor/xiaomi/MiuiCamera" remote="github" revision="pie"/>
</manifest>

**Comment by kidachiP** [comment]
<remote name="windbell-project" fetch="https://github.com/windbell-project" pushurl="ssh://git@github.com/windbell-project" revision="lineage-16.0"/>
<project path="kernel/xiaomi/msm8953" name="android_kernel_xiaomi_msm8953" remote="windbell-project" revision="lineage-16.0"/>
<project path="device/xiaomi/msm8953-common" name="android_device_xiaomi_msm8953-common" remote="windbell-project" revision="9.x"/>
<project path="device/xiaomi/tiffany" name="android_device_xiaomi_tiffany" remote="windbell-project" revision="9.x"/>
<project path="vendor/xiaomi" name="proprietary_vendor_xiaomi" remote="windbell-project" revision="lineage-16.0"/>
<project name="soshiweekly/vendor_xiaomi_MiuiCamera" path="vendor/xiaomi/MiuiCamera" remote="github" revision="pie"/>

**Comment by cakeuui0414** [comment]
uploaded

**Comment by aerzha** [comment]
> uploaded

Thanks a lot, i will have a try.
